#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-push checks..."

npm run lint
LINT_STATUS=$?

if [ $LINT_STATUS -eq 0 ]; then
  echo "Linting passed. Pushing..."
  exit 0
else
  echo "Linting failed. Please fix the errors before pushing."
  exit 1
fi
